@startuml US1003 _SSD

autonumber

actor CM as "Customer Manager"

activate CM

CM -> ":System" : requests list of job openings
activate ":System"

":System" --> CM : asks to select one of the listing options
deactivate ":System"

alt With Filters
    CM -> ":System" : selects filters (customer, date or state)
    activate ":System"

    ":System" --> CM : displays filtered data
    deactivate ":System"

    CM -> ":System" : confirms the selection
    activate ":System"

    ":System" --> CM : informs operation success
    deactivate ":System"
else No Filters
    CM -> ":System" : does not select any filters
    activate ":System"

    ":System" --> CM : displays all data
    deactivate ":System"

    CM -> ":System" : confirms the selection
    activate ":System"

    ":System" --> CM : informs operation success
    deactivate ":System"
end

deactivate CM

@enduml
