@startuml
actor CustomerManager

participant ChangePhaseStatusUI <<presentation>>
participant ChangePhaseStatusController <<application>>
database ConfigurationRepository <<repository>>
database JobOfferRepository <<repository>>
participant Configuration <<domain>>

CustomerManager -> ChangePhaseStatusUI: asks the system to open/close a phase of a job offer
activate CustomerManager
    activate ChangePhaseStatusUI

        ChangePhaseStatusUI -> ChangePhaseStatusUI: listAndChooseJobOffer()
        ChangePhaseStatusUI -> ChangePhaseStatusController: getJobOffers()
        activate ChangePhaseStatusController
            ChangePhaseStatusController -> JobOfferRepository: findAll()
            activate JobOfferRepository
                JobOfferRepository -> ChangePhaseStatusController: return jobOffers
            deactivate JobOfferRepository
        ChangePhaseStatusController -> ChangePhaseStatusUI: return jobOffers
        deactivate ChangePhaseStatusController

        ChangePhaseStatusUI -> ChangePhaseStatusUI: choosePhaseToOpenOrClose(configuration)
        ChangePhaseStatusUI -> ChangePhaseStatusController: openPhase(configuration) / closePhase(configuration)
        activate ChangePhaseStatusController

            alt Open a phase
                ChangePhaseStatusController -> Configuration: openPhase(phase)
                activate Configuration
                    Configuration -> Configuration: openPhase(phase)
                    ChangePhaseStatusController -> ChangePhaseStatusUI: return "Phase has been opened."
                deactivate Configuration
            else Close a phase
                ChangePhaseStatusController -> Configuration: closePhase(phase)
                activate Configuration
                    Configuration -> Configuration: closePhase(phase)
                    ChangePhaseStatusController -> ChangePhaseStatusUI: return "Phase has been closed."
            deactivate Configuration
            end
        deactivate ChangePhaseStatusController

        ChangePhaseStatusUI -> ConfigurationRepository: save(configuration)

        ChangePhaseStatusUI -> CustomerManager: show operation success
    deactivate ChangePhaseStatusUI
deactivate CustomerManager

@enduml
