@startuml US1021_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to display an application
activate ":System"

":System" --> Manager : requests the user to select a job opening
deactivate ":System"

Manager -> ":System" : selects the job opening
activate ":System"

":System" --> Manager : requests the user to select an application from that job opening
deactivate ":System"

Manager -> ":System" : selects the the application
activate ":System"

":System" --> Manager : shows all data from that application
deactivate ":System"

deactivate Manager

@enduml
