@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Operator" as O
participant "ListCandidatesUI" as UI <<presentation>>
participant "ListCandidatesControllerr" as CTRL <<Aplication>>
participant "AuthorizationService" as AUTH
participant "UserManagementService" as UMNG
database UserRepository as REPU <<repository>>



activate O
O-> UI : asks to list all candidates
activate UI
UI -> CTRL: listCandidatesUsers()
activate CTRL
CTRL -> AUTH: ensureAuthenticatedUserHasAnyOf()
activate AUTH
AUTH --> CTRL: returns confirmation that user is credited to perform the current operation
deactivate AUTH
CTRL -> UMNG: allUsers()
activate UMNG
UMNG -> REPU: findAll()
activate REPU
REPU --> UMNG : returns Iterable of all users
deactivate REPU
UMNG --> CTRL : returns only the candidates as a sorted list
deactivate UMNG
CTRL --> UI: returns list
deactivate CTRL
UI --> O : displays all users
@enduml