@startuml US1011_UCD

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" {
  usecase "As Customer Manager, I want to select the interview model to use for the interviews of a job opening (for their evaluation/grading)." as listJobOpenings
}

CustomerManager --> (listJobOpenings)

@enduml
