@startuml US_1011_CD

class SelectInterviewModelUI {
    -ListInterviewModelController theController
    -Scanner scanner
    +doShow() : boolean
    +listObjects(List<T> objects, String objectName) : void
    +selectObject(Scanner scanner, List<T> objects, String msg) : T
    +headline() : String
    +show() : boolean
}

class ListInterviewModelController {
    -JobOfferRepository jobOfferRepository
    -InterviewModelRepository interviewModelRepository
    +addJobOfferToInterviewModel(InterviewModel interviewModel, JobOffer jobOffer) : void
    +getListOfInterviewModelsAvailable() : List<InterviewModel>
    +getListOfAvailableJobOffers() : List<JobOffer>
}

class InterviewModel {
    -Long id
    -Reference reference
    -QuestionForm questionForm
    +InterviewModel(Reference reference, QuestionForm questionForm)
    +equals(Object o) : boolean
    +hashCode() : int
    +sameAs(Object other) : boolean
    +id() : Long
    +identity() : Long
}

class JpaInterviewModelRepository {
    +JpaInterviewModelRepository(TransactionalContext autoTx)
    +JpaInterviewModelRepository(String puname)
    +findByReference(Reference reference) : Iterable<InterviewModel>
    +findById(Long id) : Optional<InterviewModel>
}

class JpaJobOfferRepository {
    +JpaJobOfferRepository(TransactionalContext autoTx)
    +JpaJobOfferRepository(String puname)
    +findAllByManager(String managerEmail) : Iterable<JobOffer>
    +findByReference(Reference reference) : Iterable<JobOffer>
    +findAllByCreationDate(LocalDateTime creationDate) : List<JobOffer>
    +findAllByCompany(Company company) : List<JobOffer>
}

interface JobOfferRepository {
    +findAllByManager(String managerEmail) : Iterable<JobOffer>
    +findByReference(Reference reference) : Iterable<JobOffer>
    +findAllByCreationDate(LocalDateTime creationDate) : List<JobOffer>
    +findAllByCompany(Company company) : List<JobOffer>
}

interface InterviewModelRepository {
    +findByReference(Reference reference) : Iterable<InterviewModel>
    +findById(Long id) : Optional<InterviewModel>
    +findAll() : Optional<InterviewModel>
}

SelectInterviewModelUI --> ListInterviewModelController
ListInterviewModelController --> InterviewModel
ListInterviewModelController --> JobOfferRepository
InterviewModel --> JpaInterviewModelRepository
JobOfferRepository <|.. JpaJobOfferRepository
InterviewModelRepository <|.. JpaInterviewModelRepository

@enduml
