@startuml US4000_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to display candidate data
activate ":System"

":System" --> Manager : requests the user to select a job opening
deactivate ":System"

Manager -> ":System" : selects the job opening
activate ":System"

":System" --> Manager : requests the user to select a candidate that applied for that job opening
deactivate ":System"

Manager -> ":System" : selects the candidate
activate ":System"

":System" --> Manager : shows top 20 list of most referenced words
deactivate ":System"

deactivate Manager

@enduml
