@startuml US4000_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "Show top 20 list of the most frequently referenced words" as showTop20List
}

CustomerManager --> (showTop20List)

@enduml
