@startuml US_2004_SD
autonumber

actor "CustomerManager" as CM
participant "UploadRequirementTextFileUI" as UI <<presentation>>
participant "UploadRequirementTextFileController" as CTRL <<application>>
participant "UploadRequirementTextFileService" as SVC <<service>>

database RequirementModelRepository as CR <<repository>>

activate CM

CM -> UI : asks the system to upload a requirement text file
activate UI

UI --> CM : requests the user to select a file to upload
deactivate UI

CM -> UI : selects the text file to upload
activate UI

    UI -> CTRL : uploadRequirementTextFile(filepath)
    activate CTRL

        CTRL -> SVC : obtainFile(filepath)
        activate SVC
            SVC --> CTRL : file
        deactivate SVC


        CTRL -> SVC : convertFileContent(file)
        activate SVC
            SVC --> CTRL : requirementModel
        deactivate SVC

        CTRL -> SVC : saveRequirementModel(RequirementModel)
        deactivate CTRL
        activate SVC
            SVC -> CR : saveRequirementModel(RequirementModel)
            deactivate SVC
            activate CR
            deactivate CR


UI --> CM : informs operation success

deactivate UI

deactivate CM

@enduml
