@startuml US1001_SD
autonumber

actor "CustomerManager" as CM
participant "RegisterJobOpeningUI" as UI <<presentation>>
participant "RegisterJobOpeningController" as CTRL <<application>>
participant "JobOfferBuilder" as CB <<builder>>

database JobOfferRepository as CR <<repository>>

activate CM

CM -> UI : asks the system to register a job offer
activate UI

UI --> CM : requests data (function, contractType, \n mode, address, company, nrOfVacancies, \n description, requirements);
deactivate UI

CM -> UI : types request data
activate UI

    UI -> CTRL : registerJobOpening()
    activate CTRL

        CTRL -> CB : JobOfferBuilder().build()
        activate CB
        deactivate CB


        CTRL -> CR : saveJobOpening()
        deactivate CTRL
        activate CR
        deactivate CR

    deactivate CTRL

UI --> CM : informs operation success

deactivate UI

deactivate CM

@enduml
