@startuml US1002_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to create a new job offer
activate ":System"

":System" --> Manager : requests data (Job Reference, Title or function, Contract Type, Mode, \n Address, Company, Number of vacancies, Description, Requirements)
deactivate ":System"

Manager -> ":System" : types request data
activate ":System"



":System" --> Manager : shows all data and informs operation success
deactivate ":System"

deactivate Manager

@enduml
