@startuml
'https://plantuml.com/class-diagram

class AddCandidateUI{
- theController
- candidateDataWidget

+ doShow()
+ headline()
}

class CandidateDataWidget{
- email
- password
- phoneNumber
+ show()
+ email()
+ password()
+ phoneNumber()
}

class AddCandidateController{
- authz
- userSvc
+ addCandidate()
+ addCandidate()
}

class AuthorizationService{
- LOGGER
- theSession
+ AuthorizationService()
+ createSessionForUser()
+ clearSession()
+ hasSession()
+ session()
+ isAuthenticatedUserAuthorizedTo()
+ ensureAuthenticatedUserHasAnyOf()
+ loggedinUserWithPermissions()
}
class UserManagementService{
- userRepository
- encoder
- policy
+ UserManagementService()
+ registerNewUser()
+ registerNewUser()
+ registerUser()
+ activeUsers()
+ deactivatedUsers()
+ allUsers()
+ userOfIdentity()
+ deactivateUser()
+ activateUser()
}

interface UserRepository{
+ findByActive()
}
interface PasswordEncoder{
+ enconde()
+ matches()
+ upgradeEncoding()
}
interface PasswordPolicy{
+ isSatisfiedBy
}
interface CandidateRepository{
+ findByUsername()
+ findAllActive()
}
class CandidateUserManagementService{
- candidateRepository
+ registerCandidate()
}

class EmailAddress{
- serialVersionUID
- email
+ valueOf()
+ tryValueOf()
+ toString()
+ compareTO()
+ equals()
+ canEqual()
+ hashCode()
}
class PhoneNumber{
- number
+ valueOf()
+ toString()
+ equals()
+ hashCode()
}
class SystemUser{
- serialVersionUID
- version
- username
- password
- name
- email
- roles
- createdOn
- active
- deactivatedOn
- resetToken
+ init()
+ sameAs()
+ identity()
+ email()
+ assignToRole()
+ assignToRole()
+ unassignRole()
+ roleTypes()
+ toDTO()
+ passwordMatches()
+ encodedPassword() {
+ accept()
+ Username username()
+ name()
+ isActive()
+ deactivate()
+ activate()
+ hashCode()
+ equals()
+ changePassword()
+ invalidateResetToken()
+ resetPassword()
+ confirmResetPassword()
+ hasAny()
+ hasAll()
+ createdOn()
}
class CandidateUser{
- serialVersionUID
- phoneNumber
- email
- systemUser
+ CandidateUser()
+ user()
+ phoneNumber()
+ email()
+ equals()
+ hashCode()
+ sameAs()
+ emailAddress()
+ identity()
}

AddCandidateUI --|> CandidateDataWidget
AddCandidateUI --|> AddCandidateController
AddCandidateController --|> AuthorizationService
AddCandidateController --|> UserManagementService
AddCandidateController --|> CandidateUserManagementService
AddCandidateController --|> PhoneNumber
AddCandidateController --|> EmailAddress
AddCandidateController --|> CandidateUser
AddCandidateController --|> SystemUser
AddCandidateController --|> CandidateRepository
UserManagementService --|> SystemUser
UserRepository --|> SystemUser
UserManagementService --|> UserRepository
UserManagementService --|> PasswordEncoder
UserManagementService --|> PasswordPolicy
CandidateUserManagementService --|> CandidateRepository
CandidateUserManagementService --|> CandidateUser
CandidateRepository --|> CandidateUser
@enduml