    @startuml
    skinparam monochrome true
    skinparam packageStyle rectangle
    skinparam shadowing false

    actor "Admin " as Admin
    actor Operator
    actor "Customer Manager" as CustomerManager
    actor "Language Engineer" as LanguageEngineer
    actor Candidate
    actor "Applications Email Bot" as ApplicationsEmailBot
    actor Customer
    left to right direction

package Backoffice {

     usecase "Manage Customers\n and its Managers" as UC1
        Admin -- UC1

     usecase "Deploy and Configure \nPlugin" as UC2
                LanguageEngineer -- UC2

     usecase "Register Application" as UC3
            Operator -- UC3

     usecase "Manage Job\n Openings" as UC4
             CustomerManager -- UC4

}

package "Applications File Bot" {

     usecase "Import Applications\n Files" as UC5
        ApplicationsEmailBot -- UC5

}

package "Candidate App" {

     usecase "Follow Applications" as UC6
        Candidate -- UC6

}

package "Customer App" {

     usecase "Follow Job Openings" as UC7
        Customer -- UC7

}
@enduml