@startuml US1001_SD
autonumber

actor "CustomerManager" as CM
participant "RegisterJobOpeningUI" as UI <<presentation>>
participant "RegisterJobOpeningController" as CTRL <<application>>

database JobOfferRepository as CR <<repository>>
database ApplicationRepository as AR <<repository>>
database CandidateRepository as CAR <<repository>>

participant "Evaluator" as EVAL

activate CM

CM -> UI : asks the system to evaluate interviews
activate UI

UI -> CTRL : showjobOffers()
    activate CTRL

        CTRL -> CTRL : getJobOpenings()

        CTRL -> CR : getAllByManager()
        activate CR

        CR --> CTRL : list of joboffers
        deactivate CR

        CTRL --> UI : list of joboffers
        deactivate CTRL

        UI --> CM : print job offers and ask for selection
        deactivate UI

        CM -> UI : select job offer
        activate UI

        UI -> CTRL : checkIfApplicationPhaseIsOpen()
        activate  CTRL

        alt if applicationPhase is close
        CTRL --> UI : returns false

        UI --> CM : informs application phase is closed and terminates

        else if applicationPhase is open

        CTRL -> UI : returns true
        deactivate CTRL

        UI -> CTRL : getCandidatesEmail()
        activate CTRL

        CTRL -> AR : getAllEmailsByReference()
        activate AR

        AR --> CTRL : list of emails
        deactivate AR

        CTRL --> UI : list of emails
        deactivate CTRL

        UI ->CTRL : getCandidates()
        activate CTRL

        CTRL -> CAR : getAllByEmail()
        activate CAR

        CAR --> CTRL : list of candidates
        deactivate CAR

        CTRL --> UI : list of candidates
        deactivate CTRL

        UI -> CTRL : getPaths()
        activate CTRL

        CTRL --> UI : list of paths
        deactivate CTRL

        UI -> CTRL : callEvaluator()
        activate CTRL

        CTRL -> EVAL** : evaluate()
        activate EVAL

        EVAL --> CTRL : Map<EmailAddress, Double> grades
        deactivate EVAL

        CTRL --> UI : Map<EmailAddress, Double> grades
        deactivate CTRL
        UI -> CTRL : updateScores()
        activate CTRL

        CTRL -> CAR : save()
        deactivate CAR

        CTRL --> UI : inform that the evaluation is done
        deactivate CTRL
        UI --> CM : inform that the evaluation is done
deactivate UI


        end

@enduml
