@startuml
'https://plantuml.com/class-diagram

class ListCandidateInfoUI{
- theController
- listController
+ doShow()
+ headline()
}


class ListCandidateInfoController{
- authz
- userSvc
+ getCandidateByName()
}

class ListCandidatesController{
- authz
- userSvc
+ listCandidatesUsers()
}


class AuthorizationService{
- LOGGER
- theSession
+ AuthorizationService()
+ createSessionForUser()
+ clearSession()
+ hasSession()
+ session()
+ isAuthenticatedUserAuthorizedTo()
+ ensureAuthenticatedUserHasAnyOf()
+ loggedinUserWithPermissions()
}

class UserManagementService{
- userRepository
- encoder
- policy
+ UserManagementService()
+ registerNewUser()
+ registerNewUser()
+ registerUser()
+ activeUsers()
+ deactivatedUsers()
+ allUsers()
+ userOfIdentity()
+ deactivateUser()
+ activateUser()
}

interface UserRepository{
+ findByActive()
}

ListCandidateInfoUI --|> ListCandidateInfoController
ListCandidateInfoUI --|> ListCandidatesController
ListCandidatesController --|> AuthorizationService
ListCandidatesController --|> UserManagementService
ListCandidateInfoController --|> AuthorizationService
ListCandidateInfoController --|> UserManagementService
UserManagementService --|> UserRepository
@enduml