@startuml US1017_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "Upload a text file with candidate interview responses" as uploadTextFile
}

CustomerManager --> (uploadTextFile)

@enduml
