@startuml US1004_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Job Opening" as jobOpening {
  usecase "Edit a new job opening" as selectRequirementsSpecification
}

CustomerManager --> (selectRequirementsSpecification)

@enduml
