@startuml US_1000_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Administrator: as Administrator


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "I want to be able to register users of the backoffice." as UC1
  usecase "I want to be able to  disable/enable users of the backoffice." as UC2
  usecase "I want to be able to  list users of the backoffice." as UC3

}

Administrator --> (UC1)
Administrator --> (UC2)
Administrator --> (UC3)

@enduml
