@startuml US_1000_SSD_ACTIVATE_DEACTIVATE_USER

autonumber

actor Administrator as "Admin"

activate Administrator

Administrator -> ":System" : login as an Administrator in the Backoffice app
activate ":System"

":System" --> Administrator : shows Administrator Backoffice menu
deactivate ":System"

Administrator -> ":System" : selects "activate/deactive user" option
activate ":System"

":System" --> Administrator : shows activate/deactive users list
deactivate ":System"

Administrator -> ":System" : selects one user
activate ":System"

":System" --> Administrator : confirmation of the activation/deactivation of the user
deactivate ":System"



deactivate Administrator

@enduml
