@startuml US_1000_SSD_LIST_USER

autonumber

actor Administrator as "Admin"

activate Administrator

Administrator -> ":System" : login as an Administrator in the Backoffice app
activate ":System"

":System" --> Administrator : shows Administrator Backoffice menu
deactivate ":System"

Administrator -> ":System" : selects "list backoffice all users"
activate ":System"

":System" --> Administrator : shows a menu with 3 options(select all, select active or select deactive usersof the backoffice)
deactivate ":System"

Administrator -> ":System" : selects the wished option to list
activate ":System"

":System" --> Administrator : shows the list of backoffice users(activate,deactive or all) with the username,first name and last name
deactivate ":System"

deactivate Administrator

@enduml
