@startuml US_1000_SSD_ADD_USER

autonumber

actor Administrator as "Admin"

activate Administrator

Administrator -> ":System" : login as an Administrator in the Backoffice app
activate ":System"

":System" --> Administrator : shows Administrator Backoffice menu
deactivate ":System"

Administrator -> ":System" : selects "add user" option
activate ":System"

":System" --> Administrator : requests signup data (username,password,firstname,lastname,email)
deactivate ":System"

Administrator -> ":System" : types request data
activate ":System"

":System" --> Administrator : show the list of roles to choose
deactivate ":System"

Administrator -> ":System" : choose the role
activate ":System"

":System" --> Administrator : creates an user
deactivate ":System"

deactivate Administrator

@enduml
