@startuml US1012_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Job Opening" as jobOpening {
  usecase "Generate and export a template text file to help collect the candidate answers during the interviews." as selectRequirementsSpecification
}

CustomerManager --> (selectRequirementsSpecification)

@enduml
