@startuml US1008_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Language Engineer: as LanguageEngineer


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "As Language Engineer, I want to deploy and configure a plugin (i.e., Job Requirement Specification or Interview Model) to be used by the system." as ImportPlugin
}

LanguageEngineer --> (ImportPlugin)

@enduml
