@startuml US1000_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Operator: as Operator


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "As Customer Manager, I want to record the time and date for an interview with a candidate." as RegisterClient
}

Operator --> (RegisterClient)

@enduml