@startuml US1014_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to schedule an interview
activate ":System"

":System" --> Manager : displays available job openings and asks the user to select one
deactivate ":System"

Manager -> ":System" : selects job opening
activate ":System"

":System" --> Manager : verifies if job opening has any submitted applications, shows them if it does and asks for interview date and hour
deactivate ":System"

Manager -> ":System" : inputs date and hour
activate ":System"

":System" --> Manager : saves scheduled interview and returns operation success
deactivate ":System"

deactivate Manager

@enduml
