@startuml US_1009_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "I want to select the requirements specification to be used for a job opening ." as jobOpening
}

CustomerManager --> (jobOpening)

@enduml
