@startuml US_1009_SSD

autonumber

actor CustomerManager as "Customer Manager"

activate CustomerManager

CustomerManager -> ":System" : login as a Customer Manager in the Backoffice app
activate ":System"

":System" --> CustomerManager : shows Customer Manager Backoffice menu
deactivate ":System"

CustomerManager -> ":System" : selects "2. Customers" option
activate ":System"

":System" --> CustomerManager : shows Customer`s Menu
deactivate ":System"

CustomerManager -> ":System" : selects "Add Job Opening"
activate ":System"

":System" --> CustomerManager : requests information to create a Job Opening and list the job requirements that exist in the system
deactivate ":System"

CustomerManager -> ":System" : selects one of the job requirements
activate ":System"

":System" --> CustomerManager : Job opening created
deactivate ":System"





deactivate CustomerManager

@enduml
