@startuml US1001_SSD

autonumber

actor CM as "Customer Manager"

activate CM

CM -> ":System" : asks the system to register a customer
activate ":System"

":System" --> CM : requests data (name, customerCode, email, address)
deactivate ":System"

CM -> ":System" : types request data
activate ":System"

":System" --> CM : shows all data and requests confirmation
deactivate ":System"

CM -> ":System" : confirms the data
activate ":System"

":System" --> CM : informs operation success
deactivate ":System"

deactivate CM

@enduml
