@startuml US1001_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "As Customer Manager I want to register a customer and that the system automatically creates a user for that customer." as RegisterClient
}

CustomerManager --> (RegisterClient)

@enduml
