@startuml US1015_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to check the requirements of an application
activate ":System"

":System" --> Manager : requests the necessary files (candidate answers and expected answers)
deactivate ":System"

Manager -> ":System" : imports requested files
activate ":System"


":System" --> Manager : verifies the requirements and shows the result
deactivate ":System"

deactivate Manager

@enduml
