@startuml US1000_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Operator: as Operator


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "As Customer Manager, I want to rank the candidates for a job opening." as RegisterClient
}

Operator --> (RegisterClient)

@enduml