@startuml US_1019_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer Manager: as CustomerManager


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "Get an ordered list of candidates, using the job interview points (grades)." as UC1
  usecase "Analyze the candidates. " as UC2

}

CustomerManager --> (UC1)
CustomerManager --> (UC2)



@enduml
