@startuml US3000_SSD

autonumber

actor Candidate as "Candidate"

activate Candidate

Candidate -> ":System" : asks the system to display applications
activate ":System"


":System" --> Candidate : shows all data and informs operation success
deactivate ":System"

deactivate Candidate

@enduml
