@startuml US_3002_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Candidate : as Candidate


left to right direction

rectangle "Candidate App" as CandidateApp  {
  usecase "List all my applications" as UC1
}
Candidate --> (UC1)


@enduml
