@startuml US_3002_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Customer : as Customer


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "List all my job openings" as UC1
}
Customer --> (UC1)


@enduml
