@startuml US1000_UCD
'https://plantuml.com/use-case-diagram

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Operator: as Operator


left to right direction

rectangle "Backoffice" as backoffice {
  usecase "As Operator, I want to enable/disable a candidate" as RegisterClient
}

Operator --> (RegisterClient)

@enduml