@startuml US1014_SSD

autonumber

actor Manager as "Customer Manager"

activate Manager

Manager -> ":System" : asks the system to enable or deactivate a user
activate ":System"

":System" --> Manager : asks what operation use wants to do (enable/deactivate)
deactivate ":System"

Manager -> ":System" : chooses operation
activate ":System"

":System" --> Manager : displays user to enable/deactivate according to selected operation and asks user to choose whose status will be changed
deactivate ":System"

Manager -> ":System" : chooses user whose status will be changed
activate ":System"

":System" --> Manager : changes user status according to selected operation
deactivate ":System"

deactivate Manager

@enduml
