@startuml US1005_SSD

autonumber

actor CM as "Customer Manager"

activate CM

CM -> ":System" : asks the system to list an application for a job opening
activate ":System"

":System" --> CM : shows all job openings available
deactivate ":System"

CM -> ":System" : selects a job opening to view its applications
activate ":System"

":System" --> CM : shows the application information
deactivate ":System"

deactivate CM

@enduml
